import DedicatedTeam from "@/components/DedicatedTeam";
import FooterTopCta from "@/components/FooterTopCta";
import KeyServeice from "@/components/KeyServeice";
import ConversionMarketing from "@/components/service/ConversionMarketing";
import FaqSection from "@/components/service/FaqSection";
import Hero from "@/components/service/Hero";
import ListOfServeice from "@/components/service/ListOfServeice";
import MarketingCompanies from "@/components/service/MarketingCompanies";
import MarketingPlanCta from "@/components/service/MarketingPlanCta";
import OurWork from "@/components/service/OurWork";
import Payperclick from "@/components/service/Payperclick";
import Head from "next/head";
import React, { useState } from "react";

function LandingPageAgency(props) {
	const [ourWork, setourWork] = useState(props.ourWork);
	const [companies, setCompanies] = useState(props.companiesData);
	const [listOfServeice, setListOfServeice] = useState(props.listOfServeiceData);
	const [keyserveice, setKeyserveice] = useState(props.keyServeice);
	const [faqSection, setFaqSection] = useState(props.faqData);
	return (
		<div>
			<Head>
				<title>Top Landing Page Agency</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				{/* <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero
				thirdPic="/serveice/landingPageAgency/illo-PagesAndBills-Desktop.svg"
				title="We’re The Landing Page Agency
        That Makes You More Money"
				pera="When you’re focusing on digital marketing, don’t forget about landing pages.
        Landing pages with clickable call-to-actions and copy that have gone through a/b testing = unreal results."
			/>
			<OurWork ourWorkData={ourWork} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<Payperclick />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center "></div>
			<ListOfServeice listOfServeiceData={listOfServeice} bodyColor="bg-[var(--section-bg-lightblue)]"/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<KeyServeice bodyColor="bg-[var(--section-bg-lightred)]" cardColor="bg-[#ffffff]" keyServeiceData={keyserveice} />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center "></div>
			<MarketingPlanCta bodyColor="bg-[var(--section-bg-lightblue)]" title="Better Performing Landing Pages Start With Your Free Marketing Plan" />
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<ConversionMarketing
				bodyColor="bg-[var(--section-bg-lightred)]"
				cardColor="bg-[#ffffff]"
				title="Once You See Your New Dreamy Conversion Rates,
                You’ll Wonder What Else We Can Help With"
				pera="See how our dedicated marketing teams can improve your other marketing channels."
				paidAdvertising
				emailMarketing
				searchEngineOptimization
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center "></div>
			<DedicatedTeam
				bodyColor="bg-[var(--section-bg-lightblue)]"
				title="Let’s Meet n’ Greet Before We Get
                Down To Business"
				pera="Get to know your dedicated team before you sign off. This puts
                pressure on us to deliver awesomeness from the first impression."
			/>
			<div className="break_line image bg-[url('/section_break.svg')] h-[80px] bg-[length:2500px_90px]  bg-center rotate-180"></div>
			<FaqSection bodyColor="bg-[var(--section-bg-lightblue)]" faqSectionData={faqSection} />
			<FooterTopCta />
		</div>
	);
}

export async function getServerSideProps(context) {
	// let cardContent = await fetch("http://localhost:3000/api/cardcontent?slug=linkBuildingService");
	// let cardContentData = await cardContent.json();

	let data = await fetch("http://localhost:3000/api/companies?slug=ppcAgency");
	let companiesData = await data.json();

	let keyserveicedata = await fetch("http://localhost:3000/api/keyserveice?slug=landingPageAgency");
	let keyServeice = await keyserveicedata.json();

	let faqSectiondata = await fetch("http://localhost:3000/api/faqsection?slug=landingPageAgency");
	let faqData = await faqSectiondata.json();

	let ourWorkData = await fetch("http://localhost:3000/api/ourwork?slug=landingPageAgency");
	let ourWork = await ourWorkData.json();

	let listOfServeice = await fetch("http://localhost:3000/api/listofserveice?slug=landingPageAgency");
	let listOfServeiceData = await listOfServeice.json();
	return {
		props: { ourWork, companiesData, listOfServeiceData, keyServeice, faqData }, // will be passed to the page component as props
	};
}

export default LandingPageAgency;
