import Hero from "@/components/service/hero";
import React, { useEffect, useState } from "react";
import Image from "next/image";
import Payperclick from "@/components/service/Payperclick";
import MarketingCompanies from "@/components/service/MarketingCompanies";
import KeyServeice from "@/components/KeyServeice";
import { useRouter } from "next/router";
import MarketingPlanCta from "@/components/service/MarketingPlanCta";
import OthersSite from "@/components/service/OthersSite";
import ConversionMarketing from "@/components/service/ConversionMarketing";
import DedicatedTeam from "@/components/DedicatedTeam";
import FaqSection from "@/components/service/FaqSection";
import OurWork from "@/components/service/OurWork";
import ListOfServeice from "@/components/service/ListOfServeice";
import Head from "next/head";

function PpcAgency(props) {
	const [companies, setCompanies] = useState(props.companiesData);
	const [keyserveice, setKeyserveice] = useState(props.keyServeice);
	const [faqSection, setFaqSection] = useState(props.faqData);
	const [ourWork, setourWork] = useState(props.ourWork);
	const [listOfServeice, setListOfServeice] = useState(props.listOfServeiceData);

	// useEffect(() => {
	// 	fetch('http://localhost:3000/api/companies')
	// 	.then(res => res.json())
	// 	.then(data => setCompanies(data))

	//   }, [])

	return (
		<div className="section_body">
			<Head>
				<title>Top PPC Agency</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				{/* <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero
				firstPic="HappyPockets-L-updated.svg"
				secondPic="HappyPockets-R-updated.svg"
				title="We’re The PPC Agency That Puts More Dollars In Your Pocket"
				pera="Increase your conversion rates to lower your cost per conversion and get a higher conversion volume. All leading to more revenue as well."
			/>
			<OurWork ourWorkData={ourWork} />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa]"></div>
			<Payperclick />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] rotate-180"></div>
			<MarketingCompanies companiesData={companies} />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] "></div>
			<ListOfServeice listOfServeiceData={listOfServeice} />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] rotate-180 "></div>
			<KeyServeice bodyColor="bg-white" cardColor="bg-[#fafafa]" keyServeiceData={keyserveice} />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] "></div>
			<MarketingPlanCta bodyColor="bg-[#fafafa]" title="Your Custom Marketing Plan Shows The Exact Steps We’ll Take To Hit Your Goals" />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] rotate-180 "></div>
			<OthersSite
				title="Want To Expand To Other PPC Channels?  We Got You "
				pera="We can start where you're at, crush every goal you have, and then help you expand."
			/>
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] "></div>
			<ConversionMarketing
				bodyColor="bg-[#fafafa]"
				cardColor="bg-white"
				title="Improve One Channel or Rapidly Scale Performance Across All of Them at Once"
				pera="Work with specialized teams that rapidly adapt, expand, and scale as one cohesive unit."
			/>
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#fafafa] rotate-180 "></div>
			<DedicatedTeam
				bodyColor="bg-white"
				title="Meet Your Dedicated Team Before We Start Making You More Money"
				pera="Be confident in the people behind your marketing.Test their experience, their approach, and their humor."
			/>
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#F9FCFF] "></div>
			<FaqSection bodyColor="bg-[#F9FCFF]" faqSectionData={faqSection} />
			<div className="break_line image bg-[url('/page_broke.png')] h-[75px] bg-[length:1600px_90px] bg-center bg-[#F9FCFF] rotate-180"></div>
		</div>
	);
}

export async function getServerSideProps(context) {
	let data = await fetch("http://localhost:3000/api/companies?slug=ppcAgency");
	let companiesData = await data.json();

	let keyserveicedata = await fetch("http://localhost:3000/api/keyserveice?slug=ppcAgency");
	let keyServeice = await keyserveicedata.json();

	let faqSectiondata = await fetch("http://localhost:3000/api/faqsection?slug=ppcAgency");
	let faqData = await faqSectiondata.json();

	let ourWorkData = await fetch("http://localhost:3000/api/ourwork?slug=ppcAgency");
	let ourWork = await ourWorkData.json();

	let listOfServeice = await fetch("http://localhost:3000/api/listofserveice?slug=ppcAgency");
	let listOfServeiceData = await listOfServeice.json();
	return {
		props: { companiesData, keyServeice, faqData, ourWork, listOfServeiceData }, // will be passed to the page component as props
	};
}

export default PpcAgency;
